### ISSUE TITLE
Validate reference link in request (must start with https:// )

### ISSUE THREAD

**Issue by elliotBraem** [near-everything/app#10]

**Comment by ameer-khan-ashraf** [comment]
Hi I would like to work on this. Is there a contribution guide?

**Comment by elliotBraem** [comment]
Hi, yeah! I have a short bit in the README atm, but will work on getting a full one out soon. as well as much more documentation. Go ahead and fork then create a PR, thanks for contributing!

**Comment by ameer-khan-ashraf** [comment]
when I tried sumbitting an image before working on the fix, I am getting the following error.
![image](https://user-images.githubusercontent.com/22253530/182092886-70a5cf8f-43a2-4b9f-8404-d2d60e9f6e7f.png)

**Comment by elliotBraem** [comment]
This was an issue because you were not logged in; I just fixed this issue with #6, so now navigating to collect or request page will redirect you to /login if you are not logged in. 

Also did a bit of updating the documentation for ya, so please check it out; if you want to submit an image, you'll need to run the [everything-api](https://github.com/near-everything/api), start the docker container, and then run this application. After that, login with whatever phone number (real or fake, doesn't matter). I made a gif to show how that login works.

Please let me know if anything else comes up!! Really appreciate the interest!

**Comment by ameer-khan-ashraf** [comment]
This really helps. Thanks for updating the documentation

**Comment by ameer-khan-ashraf** [comment]
I followed the instructions and setup the api and Started the app. The authentication succeeded without a hitch but I faced an issue where the request was still trying to connect to the firebase server instead of the emulator. This was because the storage was being called from firebase.js in request instead of firebaseClient.js similar to collect. After updating that the image uploading is working but I am getting errors from graphql. How do I setup and connect graphql?

**Comment by elliotBraem** [comment]
Ah, so while the PostgreSQL server was starting in api's docker-compose, it was not bootstrapping the sql schema. Since this project is using Postgraphile which automatically generates a GraphQL API based on sql schema, there was no API being generated. 

This morning, I merged [PR #5](https://github.com/near-everything/api/commit/7ed854d00b21b445248794b18dd1f95b41163708) which bootstraps the SQL schema in the volume on docker-compose up. Updated some documentation and cleaned some more things up; you may want to clear any volumes associated with this project first, but run "npm run docker:up" and this should setup and connect the GraphQL API.

Also, thanks for pointing out the request issue, I went ahead and fixed that and merged in #15.

Please let me know if anything else comes up, although I believe everything should work now! I did a fresh clone and install from scratch of both the projects on my machine and I did not run into any issues... hopefully you won't either!

**Comment by ameer-khan-ashraf** [comment]
Oh I just docker composed the the containers and didn't run the actual server 😅. The graphql requests are going through now. Can you also explain how the collect and request functions work? Like do I have to collect a file before requesting it ? Also what is the use for the reference URL?

**Comment by elliotBraem** [comment]
Hahah no problem. 
Sure, so I will get an architecture diagram up soon (maybe by EOD, just need to find where to put it) to help illustrate this, but in the meantime, here's some explanation of what this project is all about:

We are creating an inventory of everything: a centralized database of real, tangible assets that can be queried by various marketplaces, services, tools, etc.-- in the effort to create a circular economy that makes sense for everyone.

In other words, collect is a tool for people to take pictures of their things (clothes, furniture, electronics, recyclables... literally anything). They attach a category, subcategory, and maybe some attributes to describe the thing. When they submit, the thing is added to the PostgreSQL database.

request is a tool for people to request things they want-- they could attach a screenshot of the product, input a reference link (like a link to an amazon page), or they can describe what they are looking for. When they submit, the request is added to the PostgreSQL database.

organize then queries this database and allows users to sift through the things and requests and make edits to them (WIP). They can change category, subcategory, add characteristics... anything in order to create a well organized and uniform DB of things people have and things people want. Eventually, we'll be able to match these two together and broker deals. 

Eventually, once a thing is adequately labelled and organized, it will be minted to blockchain and indexed by a subgraph, which can then be queried by any marketplace, service, tool.... private data will continue to be stored in Postgres and is available for query as well. It seems from your twitter that you like Web3.0, I think you can fill in the details of why these items being on chain will be so significant 😄 

Seriously appreciate the interest in the project!! I'm just starting to "launch it", so if you like the idea, then consider joining the [Discord](https://discord.gg/pEGGmMGDfy). You're one of the first contributors, would love to keep working with you; will be keeping the issues flowing, there's a ton to be done.

**Comment by ameer-khan-ashraf** [comment]
Thanks for the explanation. Really interesting Idea and I would like to be involved in the idea. will keep an eye out for more issues to contribute  :smile: . I have joined the discord and just finished up this issue and opened a pull request so have a look. Really excited to see the project take off.
