### ISSUE TITLE
Create request page

### ISSUE THREAD

**Issue by elliotBraem** [near-everything/app#22]
In pages/requests/[id].js

Currently is an empty page. Will need to be configured to grab the id from the router and fetch the request's details.

Recreate this page to show a "Request's" details, the details will come from a new graphQL query "useRequestById()".

Bonus points if prerending is implemented with getServerSideProps, otherwise can be saved for other story.

**Comment by ameer-khan-ashraf** [comment]
I would like to work on this

**Comment by elliotBraem** [comment]
Awesome, will assign. Let me know if you need any more info -- getting started should be similar to pages/items/[id].js. This story is very similar to #21, although this one is an empty slate. 

Only other info I can think of could maybe be the query to use? useRequestById will need to be created and can use a graphQL query looking like this:

```
query requestById($requestId: Int!) {
  request(id: $requestId) {
    id
    media
    referenceLink
    description
  }
}
```

**Comment by ameer-khan-ashraf** [comment]
The hook is made and I am able to fetch data. I have also rendered the data but styling is still pending.
![image](https://user-images.githubusercontent.com/22253530/182902143-586e82ba-2333-468a-81db-aab1ff0d3641.png)
Anything else I have to do before I make a pull request? Should I run through linter again?

**Comment by elliotBraem** [comment]
Awesome, looks good to me -- yeah just run the linter then should be good to go. Not worried about styles for anything atm, will be recruiting designers soon, I'm sure there will be plenty of changes so no point wasting time.
