### ISSUE TITLE
On mobile, fix the extra spaces around "privacy policy" text (see image)

### ISSUE THREAD

**Issue by elliotBraem** [near-everything/app#36]
MUST BE RUNNING FIREBASE EMULATOR via Docker, see details in [everything api](https://github.com/near-everything/api) 

On /login, enter in a phone number (any number, real or fake), press submit. This will bring up confirmation code input and show the checkbox for privacy policy. Notice the extra space, please remove them.
![Image](https://user-images.githubusercontent.com/16282460/182912633-47e7b28e-2ce9-4372-b6ae-8afd3cf082ad.jpeg)

This screenshot is from an iPhone 13 Pro

**Comment by ameer-khan-ashraf** [comment]
Cant reproduce this issue. Is it fixed?
