### ISSUE TITLE
Create tooltips on collect, request, and organize pages

### ISSUE THREAD

**Issue by elliotBraem** [near-everything/app#55]
In top right corner of collect, request, and organize pages, I want to put a question mark icon that serves as a tooltip. 

Clicking this icon brings up the descriptions:

collect: "A tool for adding something to the inventory of everything."
request: "A tool for requesting something from the inventory of everything."
organize: "A tool for organizing things and requests in the inventory of everything."

**Comment by NereidaRondon** [comment]
Hello... I would like to complete this task! I'm forking now... Thank you for the opportunity.
